[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tinytroupe"]
include-package-data = true

[project]
name = "tinytroupe"
version = "0.5.2"
authors = [
  { name="Paulo Salem", email="paulo.salem@microsoft.com" }
]
description = "LLM-based people simulation for design, validation and insight generation in business."
readme = "README.md"
requires-python = ">=3.11,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas >=2.0,<3.0",
    "pytest >=8.0,<9.0",
    "pytest-cov >=7.0,<8.0",
    "openai >=1.65,<3.0",
    "tiktoken >=0.12,<1.0",
    "msal >=1.30,<2.0",
    "rich >=14.0,<15.0",
    "requests >=2.30,<3.0",
    "chevron >=0.14,<1.0",
    "llama-index >=0.14,<1.0",
    "llama-index-embeddings-huggingface >=0.6,<1.0",
    "llama-index-readers-web >=0.5,<1.0",
    "llama-index-embeddings-azure-openai >=0.4,<1.0",
    "pypandoc >=1.15,<2.0",
    "markdown >=3.9,<4.0",
    "jupyter >=1.1,<2.0",
    "matplotlib >=3.10,<4.0",
    "pydantic >=2.12,<3.0",
    "textdistance >=4.6,<5.0",
    "scipy >=1.16,<2.0",
    "python-docx >=1.2.0,<2.0.0"
]


[project.urls]
"Homepage" = "https://github.com/microsoft/tinytroupe"


[tool.pytest.ini_options]
pythonpath = [
  "."
]

testpaths = [
  "./tests/"
]

markers = [
  "examples: mark a test as the execution of examples",
  "notebooks: mark a test as a more specific Jupyter notebook execution example",
]
addopts = "--cov=tinytroupe --cov-report=html --cov-report=xml"